#! /bin/dash
# Starts the environment
# (c) tudurom 2016 - wtfpl
#

compton -b
sxhkd -c ~/.config/sxhkd/wmutils_sxhkd &
urxvtd &
#wew | focus_watcher.sh &
wew | wewhandle &
feh  --bg-scale '/home/tanay/usr/media/pictures/Chrome/20130206-211837_Rust Knot_high_resolution.jpg'
xwait

# vim: set ft=sh :
