#! /bin/dash
#
# handle wew events
# (c) tudurom 2016 - wtfpl
#
while IFS=: read -r ev wid; do
  case $ev in
    # Window creation
    16)
      if ! wattr o $wid; then
        corner.sh md $wid
      fi
      ;;

    # Mapping request aka group activated
    19)
      if ! wattr o $wid; then
        focus.sh $wid
      fi
      ;;

    # Window closed
    18)
      if ! wattr $(pfw); then
        focus.sh prev
        #groups.sh # Force cleanup
      fi
      ;;
  esac
done

# vim: set ft=sh :
